// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UPCService;

namespace UPCService.Migrations
{
    [DbContext(typeof(ProyectoDBContext))]
    [Migration("20190530025608_AddEntities")]
    partial class AddEntities
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("UPCService.Models.Distrito", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nombre");

                    b.HasKey("Id");

                    b.ToTable("Distritos");
                });

            modelBuilder.Entity("UPCService.Models.Publicacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CostoServicio");

                    b.Property<string>("Descripcion");

                    b.Property<int>("EstaHabilitado");

                    b.Property<int?>("PublicistaId");

                    b.Property<int?>("ServicioId");

                    b.Property<string>("Titulo");

                    b.HasKey("Id");

                    b.HasIndex("PublicistaId");

                    b.HasIndex("ServicioId");

                    b.ToTable("Publicaciones");
                });

            modelBuilder.Entity("UPCService.Models.Reseña", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ClienteId");

                    b.Property<string>("Contenido");

                    b.Property<int?>("PublicacionId");

                    b.Property<float>("Valoracion");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("PublicacionId");

                    b.ToTable("Reseñas");
                });

            modelBuilder.Entity("UPCService.Models.Servicio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Descripcion");

                    b.Property<string>("Nombre");

                    b.HasKey("Id");

                    b.ToTable("Servicios");
                });

            modelBuilder.Entity("UPCService.Models.Solicitud", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ClienteId");

                    b.Property<string>("Mensaje");

                    b.Property<int?>("PublicacionId");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("PublicacionId");

                    b.ToTable("Solicitudes");
                });

            modelBuilder.Entity("UPCService.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Apellidos");

                    b.Property<string>("Contrasena");

                    b.Property<int?>("DistritoId");

                    b.Property<string>("Email");

                    b.Property<string>("Nombre");

                    b.Property<int>("Rol");

                    b.Property<string>("Telefono");

                    b.Property<string>("UrlContacto");

                    b.HasKey("Id");

                    b.HasIndex("DistritoId");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("UPCService.Models.Publicacion", b =>
                {
                    b.HasOne("UPCService.Models.Usuario", "Publicista")
                        .WithMany()
                        .HasForeignKey("PublicistaId");

                    b.HasOne("UPCService.Models.Servicio", "Servicio")
                        .WithMany()
                        .HasForeignKey("ServicioId");
                });

            modelBuilder.Entity("UPCService.Models.Reseña", b =>
                {
                    b.HasOne("UPCService.Models.Usuario", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId");

                    b.HasOne("UPCService.Models.Publicacion", "Publicacion")
                        .WithMany()
                        .HasForeignKey("PublicacionId");
                });

            modelBuilder.Entity("UPCService.Models.Solicitud", b =>
                {
                    b.HasOne("UPCService.Models.Usuario", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId");

                    b.HasOne("UPCService.Models.Publicacion", "Publicacion")
                        .WithMany()
                        .HasForeignKey("PublicacionId");
                });

            modelBuilder.Entity("UPCService.Models.Usuario", b =>
                {
                    b.HasOne("UPCService.Models.Distrito", "Distrito")
                        .WithMany()
                        .HasForeignKey("DistritoId");
                });
#pragma warning restore 612, 618
        }
    }
}
